### ISSUE TITLE
The "free" version feels like visiting a mainstream media page without an adblocker

### ISSUE THREAD

**Issue by Leonetienne** [chevereto/chevereto#78]
where's the point in self-hosting it then, anyway. rm'ed it gets...

**Comment by rodber** [comment]
Hello,

Just to clarify, there are no ads in Chevereto free edition, so it’s hard to understand how it could feel that way. I assume you’re referring to the “$Pro” links in the menu. If that’s the case, you might want to check out this discussion: https://github.com/chevereto/chevereto/issues/77.

I’ve actively worked on removing certain paid prompts, allowing logo edits, and supporting external storage servers—it’s all there in the issues section for transparency.

But I have to say, your comment makes me rethink those efforts. For you, this might just be another software you stumbled across yesterday, but for me, this is a product I’ve been building since 2007—it’s my life’s work.

Thanks for sharing your thoughts.

**Comment by Leonetienne** [comment]
Thanks for your reply. What i mean is that the free version is littered with calls-to-actions which all prompt the user to buy a (btw rly expensive license. it's half phpstorms cost). And that in combination with the fact the free versions public frontend is basically a giant billboard for chevereto.com, with some user-defined pictures. I would not say that the free version is a viable tool to share photography for the average self-hoster because of that.

> But I have to say, your comment makes me rethink those efforts. For you, this might just be another software you stumbled across yesterday, but for me, this is a product I’ve been building since 2007—it’s my life’s work.

yes, exactly. I just discovered this last night and spent 3am to 4:30 am getting it to run just to discover, i basically can't do anything with it, because it doesn't allow me to. That made me a bit upset and i am sorry for that.

**Comment by rodber** [comment]
Thanks for your feedback, and I understand your frustration.

For context, all the issues you mentioned regarding prompts and limitations are already being considered and discussed in our issue tracker. If you're interested, you can review those ongoing discussions here: https://github.com/chevereto/chevereto/issues.
